# Generated by Django 4.1.7 on 2023-03-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_exampendingsubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total_correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='total_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
